apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-initscripts
  labels:
    app: exemple-app
    team: devops
spec:
  selector:
    matchLabels:
      name: ds-initscripts
  template:
    metadata:
      labels:
        name: ds-initscripts
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: my-pool
      containers:
      - name: initscripts-ds
        image: gcr.io/google-containers/startup-script:v1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            sysctl -w vm.max_map_count=262144
            sysctl -w vm.dirty_background_ratio=5 # Default value: 5
            sysctl -w vm.dirty_ratio=70 # Default value: 20
            sysctl -w net.core.wmem_max=2097152 # Default value: 212992
            sysctl -w net.core.netdev_max_backlog=2000 # Default value: 1000
            echo "done"
