apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exemple-api-hpa
  labels:
    app: exemple-api-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exemple-api-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
