apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer-api-service
  labels:
    app: consumer-api-service
    team: order-payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer-api-service
        team: order-payment
    spec:
      containers:
      - name: consumer-api-service
        image: gcr.io/fyndiq-dev/consumer-api-service:latest
        env:
        - name: KAFKA_BROKERS
          value: "kafka-0.broker.kafka:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://schema-registry-lb:8081/"
        - name: DATADOG_HOST
          value: dd-agent-lb.default.svc.cluster.local
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: consumer-api-service
              key: sentry_dsn
        - name: SENTRY_ENV
          value: "dev"
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
