apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-service
  labels:
    app: wordpress-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-service
        team: order-payment
    spec:
      containers:
      - name: wordpress-service
        image: wordpress:latest
        env:
        - name: DB_HOST
          value:
        - name: DB_USERNAME
          value:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
