apiVersion: v1
kind: Service
metadata:
  name: consumer-api-service
  labels:
    app: consumer-api-service
    team: order-payment
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    name: http
  selector:
    app: consumer-api-service
