apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
    - targetPort: 80
  selector:
    app: wordpress
    tier: frontend
